### PR TITLE
add argument 'length_exception'

### PR DESCRIPTION
**Pull request by EpsIotaPi**
add the argument 'length_exception' at Readability class, Allow users to choose whether the program throws an exception or issues a warning when the text length is less than 100 words.

### CODE REVIEW

**Comment by EpsIotaPi** [comment]
and could fix #1 #14

**Comment by cdimascio** [comment]
This looks good, however please rename to min_words, where min_words is the minimum number of words. Clients can set min_words to 0 to avoid the exception. Set min_words default to 100

**Comment by EpsIotaPi** [comment]
Thank you for your comment!
I change the length_exception to min_words as your request. I also add an "ignore_length" argument to SMOG test, this argument is for avoid length limit of SMOG test. If you think this is not a good idea, you can delete this argument.

**Review by cdimascio — APPROVED** [review]

**Comment by antonioFlavio** [comment]
Hi, Last version available on pip is 1.4.5 from Aug 2020.

**Pull request merged**
